
# Window settings
WINDOW_WIDTH = 500
WINDOW_HEIGHT = 500


# UI settings
TITLE_SIZE_PROPORTION = 4/10
TITLE_COLOR = '#deadbe'

BUTTON_TEXT_COLOR = '#babdb6'
BUTTON_BASE_COLOR = '#204a87'
BUTTON_OVER_COLOR = '#3465a4'
BUTTON_DOWN_COLOR = '#729fcff'
